### ISSUE TITLE
Update survey questions object to latest version and address potential user edge case issues

### ISSUE THREAD

**Issue by jdhern17** [codefordenver/expunge-colorado-screener#23]
- the current SURVEY_DATA object inside of the survey.js file (updated initially on branch issue9/scaffold-survey-data-obj from #9 ) should be updated to align with the latest versions of the files:
     - Expunge CO Screener- Questions and Logic.xlsx
     - Expunge Colorado Question Logic.pdf

Additional considerations:
- there may be an issue where users that return to previous questions to change responses will change the visibility of subsequent questions, however, the visibleIf property would still be reading the values from the hidden responses.
- a way to potentially simplify the object and also lower the incidence of the hidden responses issue could be to put all questions on a separate page (although the issue may persist with the availability of a previous button).

**Comment by eemshi** [comment]
This might actually be intertwined with #13 so @kadrianne and I can take a look
