### ISSUE TITLE
Update demographics County question with "N/A" option & race/ethnic background typo

### ISSUE THREAD

**Issue by kadrianne** [codefordenver/expunge-colorado-screener#57]
In demographics survey:
2. I identify my race/ethnic background as:
Fix typo "Native Hawaiian or Other Pacific Islander"

4. What county in Colorado did your case take place in?
Add "N/A" Option after "Prefer not to answer"

**Comment by markogrady1** [comment]
is ok if i work on this one @kadrianne ?

**Comment by kadrianne** [comment]
@markogrady1 go for it!

**Comment by kadrianne** [comment]
Updated issue to fix typo in another question
